import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { buildVersionedCatalogs } from "./catalog.mjs";

const outputPath = join(process.cwd(), "src", "generated", "catalog.ts");
const catalogs = await buildVersionedCatalogs(process.cwd());

const source = `/* This file is generated by scripts/generate-catalog.mjs. Do not edit manually. */
import type { VersionedCatalogs } from "../types";

export const catalogVersions = ${JSON.stringify(catalogs, null, 2)} satisfies VersionedCatalogs;
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);

console.log(`Generated ${outputPath}`);
