import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { buildCatalog } from "./catalog.mjs";

const outputPath = join(process.cwd(), "src", "generated", "catalog.ts");
const catalog = await buildCatalog(process.cwd());

const source = `/* This file is generated by scripts/generate-catalog.mjs. Do not edit manually. */
import type { SkillTreeCatalog } from "../types";

export const catalog = ${JSON.stringify(catalog, null, 2)} satisfies SkillTreeCatalog;
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);

console.log(`Generated ${outputPath}`);
