import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

const iconsDir = join(process.cwd(), "assets", "skilltree-icons");
const outputPath = join(process.cwd(), "src", "generated", "skilltree-icons.ts");

function parseSvg(fileName, source) {
  const viewBoxMatch = source.match(/\sviewBox=(["'])(.*?)\1/);
  const bodyMatch = source.match(/<svg\b[^>]*>([\s\S]*)<\/svg>\s*$/);

  if (!viewBoxMatch || !bodyMatch) {
    throw new Error(`${fileName} must be an SVG with a viewBox`);
  }

  return {
    viewBox: viewBoxMatch[2],
    body: bodyMatch[1]
  };
}

const fileNames = (await readdir(iconsDir)).filter((fileName) => fileName.endsWith(".svg")).sort((a, b) => a.localeCompare(b));
const icons = {};

for (const fileName of fileNames) {
  const key = fileName.replace(/\.svg$/, "");
  const source = await readFile(join(iconsDir, fileName), "utf8");
  icons[key] = parseSvg(fileName, source.trim());
}

const source = `/* This file is generated by scripts/generate-icons.mjs. Do not edit manually. */

export interface SkilltreeIcon {
  viewBox: string;
  body: string;
}

export const skilltreeIcons: Record<string, SkilltreeIcon> = ${JSON.stringify(icons, null, 2)};
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);

console.log(`Generated ${outputPath}`);
